[Zsh] Config tidy-ups.

diff --git a/system/dotfiles/usr/share/Zsh/zshrc b/system/dotfiles/usr/share/Zsh/zshrc
--- a/system/dotfiles/usr/share/Zsh/zshrc
+++ b/system/dotfiles/usr/share/Zsh/zshrc
@@ -155,29 +155,18 @@ export MANPATH=$(build_path "${manpath_dirs[@]}")
 
 
 # --------------------------------------------------------------------------
-# Plugins.
+# Conda setup.
 # --------------------------------------------------------------------------
 
-# Ohmyzsh plugins, found in ~/.oh-my-zsh/plugins/*
-# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
-plugins=(
-    autoenv
-    debian    # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#debian
-    docker    # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#docker
-    emacs     # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/emacs
-    extract   # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#extract
-    git       # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git/
-    git-extras  # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#git-extras
-    git-flow  # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#git-flow
-    github    # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#github
-    jsontools # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#jsontools
-    history   # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#history
-    pyenv     # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#pyenv
-    python    # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#python
-    tmux      # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#tmux
-    z         # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/z
-    zsh-syntax-highlighting
-)
+# This uses a modified version of the shell init function generated by conda
+# that skips a slow check. See:
+# https://github.com/conda/conda/issues/7855#issuecomment-456085432
+if [ -f "$HOME/anaconda3/etc/profile.d/conda.sh" ]; then
+    . "$HOME/anaconda3/etc/profile.d/conda.sh"
+else
+    export PATH="$HOME/anaconda3/bin:$PATH"
+fi
+
 
 # --------------------------------------------------------------------------
 # Key bindings.
@@ -438,22 +427,6 @@ pdf_concat() {
     set +x
 }
 
-# Set CUDA_VISIBLE_DEVICES.
-unalias gpu
-gpu() {
-    if [[ "$1" == 0 ]] || [[ "$1" == 1 ]]; then
-        export CUDA_VISIBLE_DEVICES="$1"
-    elif [[ -z "$1" ]]; then
-        export CUDA_VISIBLE_DEVICES=
-    else
-        echo 'Invalid GPU!' >&2
-    fi
-}
-# By default, disable GPU.
-if [[ -d /usr/local/cuda ]]; then
-    export CUDA_VISIBLE_DEVICES=
-fi
-
 # List file and directory contents.
 unalias l
 l() {
@@ -609,70 +582,6 @@ fi
 # Add autojump, if available. <https://github.com/wting/autojump>
 [ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh
 
-# --------------------------------------------------------------------------
-# External files.
-# We do these last so that they can override the default settings such as
-# updating $PATH.
-# --------------------------------------------------------------------------
-
-setopt nullglob
-
-# Custom zsh scripts
-if test -d ~/.zsh; then
-    for script in ~/.zsh/*.zsh; do
-        test -r "$script" && . "$script"
-    done
-
-    for script in ~/.zsh/private/*.zsh; do
-        test -r "$script" && . "$script"
-    done
-    unset script
-fi
-
-unsetopt nullglob
-
-fpath[1,0]=~/.zsh/
-
-
-
-# compinit optimization for oh-my-zsh
-# On slow systems, checking the cached .zcompdump file to see if it must be
-# regenerated adds a noticable delay to zsh startup.  This little hack restricts
-# it to once a day.  It should be pasted into your own completion file.
-#
-# Author: https://github.com/15cm
-# See: https://gist.github.com/15cm/88e320d71fe7fe5a4bb24b99da6b93f0
-#
-#autoload -U compaudit compinit
-#: ${ZSH_DISABLE_COMPFIX:=true}
-# ...
-setopt extendedglob
-if [[ $ZSH_DISABLE_COMPFIX != true ]]; then
-  # If completion insecurities exist, warn the user without enabling completions.
-  if ! compaudit &>/dev/null; then
-    # This function resides in the "lib/compfix.zsh" script sourced above.
-    handle_completion_insecurities
-  # Else, enable and cache completions to the desired file.
-  else
-    if [[ -n "${ZSH_COMPDUMP}"(#qN.mh+24) ]]; then
-      compinit -d "${ZSH_COMPDUMP}"
-      compdump
-    else
-      compinit -C
-    fi
-  fi
-else
-  if [[ -n "${ZSH_COMPDUMP}"(#qN.mh+24) ]]; then
-    compinit -i -d "${ZSH_COMPDUMP}"
-    compdump
-  else
-    compinit -C
-  fi
-fi
-
-[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
-
-[[ -s "/etc/grc.zshrc" ]] && source /etc/grc.zshrc
 
 # --------------------------------------------------------------------------
 # Shell environment.
@@ -728,6 +637,105 @@ if [[ -x $(which rbenv) ]]; then
     eval "$(rbenv init -)"
 fi
 
+
+# --------------------------------------------------------------------------
+# Plugins.
+# --------------------------------------------------------------------------
+
+# Defer plugin initialization so that the shell is fully configured with all
+# of the expected paths etc.
+
+# Ohmyzsh plugins, found in ~/.oh-my-zsh/plugins/*
+# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
+plugins=(
+    autoenv
+    debian    # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#debian
+    docker    # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#docker
+    emacs     # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/emacs
+    extract   # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#extract
+    git       # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git/
+    git-extras  # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#git-extras
+    git-flow  # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#git-flow
+    github    # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#github
+    jsontools # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#jsontools
+    history   # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#history
+    pyenv     # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#pyenv
+    python    # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#python
+    tmux      # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins#tmux
+    z         # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/z
+    zsh-syntax-highlighting
+)
+
+
+# --------------------------------------------------------------------------
+# External files.
+# We do these last so that they can override the default settings such as
+# updating $PATH.
+# --------------------------------------------------------------------------
+
+setopt nullglob
+
+# Custom zsh scripts
+if test -d ~/.zsh; then
+    for script in ~/.zsh/*.zsh; do
+        test -r "$script" && . "$script"
+    done
+
+    for script in ~/.zsh/private/*.zsh; do
+        test -r "$script" && . "$script"
+    done
+    unset script
+fi
+
+unsetopt nullglob
+
+fpath[1,0]=~/.zsh/
+
+[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
+
+[[ -s "/etc/grc.zshrc" ]] && source /etc/grc.zshrc
+
+[ -f "$BREW_PREFIX"/opt/autoenv/activate.sh ] && source "$BREW_PREFIX"/opt/autoenv/activate.sh
+
+# compinit optimization for oh-my-zsh
+# On slow systems, checking the cached .zcompdump file to see if it must be
+# regenerated adds a noticable delay to zsh startup.  This little hack restricts
+# it to once a day.  It should be pasted into your own completion file.
+#
+# Author: https://github.com/15cm
+# See: https://gist.github.com/15cm/88e320d71fe7fe5a4bb24b99da6b93f0
+#
+#autoload -U compaudit compinit
+#: ${ZSH_DISABLE_COMPFIX:=true}
+# ...
+setopt extendedglob
+if [[ $ZSH_DISABLE_COMPFIX != true ]]; then
+  # If completion insecurities exist, warn the user without enabling completions.
+  if ! compaudit &>/dev/null; then
+    # This function resides in the "lib/compfix.zsh" script sourced above.
+    handle_completion_insecurities
+  # Else, enable and cache completions to the desired file.
+  else
+    if [[ -n "${ZSH_COMPDUMP}"(#qN.mh+24) ]]; then
+      compinit -d "${ZSH_COMPDUMP}"
+      compdump
+    else
+      compinit -C
+    fi
+  fi
+else
+  if [[ -n "${ZSH_COMPDUMP}"(#qN.mh+24) ]]; then
+    compinit -i -d "${ZSH_COMPDUMP}"
+    compdump
+  else
+    compinit -C
+  fi
+fi
+
+# The command should exit with a zero returncode, otherwise the first line of
+# prompt will be "Previous command exited with return code X", which can be a
+# bit confusing since the user hasn't yet typed anything in.
+true
 
 ### === End profiled region ===
 # Uncomment the following two lines (and the one line at the start of this
